# + -------------------------------------------------------------------------------- + #
# | MESSAGE, ERRORMESSAGE SETTINGS ( 메시지 설정 )
# | 유저에게 출력되지 않을 메세지는 해당 라인을 지우시거나
# | 해당 라인의 제일 앞에 '#' 을 붙여 주석으로 처리하시면 됩니다.
# | ㄴ 아래 restorePrivateItem을 참고해주세요.
# + -------------------------------------------------------------------------------- + #
messages:
  # (메시지 앞에 붙는) 접두사
  prefix: ' &c귀속&f아이템 &6| &r'

  # 귀속 아이템을 설정하였을 때 출력되는 메시지
  setPrivateItem: '손에 든 아이템을 귀속아이템을 설정하였습니다!'

  # 귀속 아이템을 가지고 죽을 시 출력되는 메시지
  # restorePrivateItem: '&f죽기 전 인벤토리에 있던 귀속 아이템이 복구되었습니다.'

  # 콘피그를 리로드 하였을 때 출력되는 메시지
  reloadComplete: '&a콘피그를 리로드하였습니다.'

errorMessages:
  # 권한이 없을 때 출력되는 메시지
  notAnOperator: '&c해당 명령어를 실행할 권한이 없습니다.'

  # 콘솔에서 불가능 명령어를 사용하였을 때 출력되는 메시지
  noConsoleMessage: '&c콘솔에서는 불가능한 명령어입니다. (인게임에서 시도해주세요)'

  # 귀속아이템을 설치할 수 없을 때 출력되는 메시지
  noPlacePrivateItem: '&c귀속아이템은 설치 할 수 없습니다.'

  # 귀속 아이템을 옮기려고 했을 때 출력되는 메시지
  noMovePrivateItem: '&c귀속아이템은 다른 인벤토리에 놓을 수 없습니다.'

  # 귀속 아이템을 버리려고 했을 때 출력되는 메시지
  noDropPrivateItem: '&c귀속아이템은 버릴 수 없습니다.'

  # 잘못된 명령어를 사용하였을 때 출력되는 메시지
  wrongCommand: '&c잘못된 명령어입니다. (다시 시도해주세요)'